# **In Class Activity: Data Preprocessing**

## **PAIR ASSIGNMENT**

Please work in pairs for this exercise. Pair up with the person next to you. If you find that there isn't anyone sitting next to you or if you're unable to form a pair, please raise your hand, and I will assist in pairing you with someone.


### **Task 0: Please assign your full name and your partner's full name to the variables below, respectively.**


Example:

```
your_name = 'Taylor Swift'
your_partner_name = 'Travis Kelce'
```

In [ ]:
# Assign your and your partner's names here.  If you find that there isn't anyone sitting next to you or if you're unable to form a pair, please raise your hand.
# If, in the end, we are unable to find a partner for you, please assign the word "self" to the `your_partner_name` variable.
your_name = 'Jonathan Cruz'
your_partner_name = ''

## **Dataset: modified_automobile.csv**


This version of the automobile dataset contains various attributes of automobiles with introduced inconsistencies for the sake of this exercise.

In [1]:
import pandas as pd


modified_df = pd.read_csv('modified_automobile.csv')
modified_df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,NaN,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72.0,4200.0,31,39,18344.0
1,1,128.0,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,NaN,5200.0,31,37,7799.0
2,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750.0
3,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,NaN,4800.0,28,34,9258.0
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0

### 1. **Handling Missing Values**

In [2]:
count_missing_values = modified_df.isna().sum()

In [3]:
modified_df_dropna = modified_df.dropna()

In [4]:
modified_df_fill_mean = modified_df.copy()

In [5]:
modified_df_fill_median = modified_df.copy()

In [6]:
modified_df_dropna.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0
5,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
6,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.0,101.0,5800.0,24,28,12945.0
7,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0
8,2,94.0,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68.0,4500.0,37,42,9495.0

In [7]:
modified_df_fill_mean.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,NaN,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72.0,4200.0,31,39,18344.0
1,1,128.0,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,NaN,5200.0,31,37,7799.0
2,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750.0
3,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,NaN,4800.0,28,34,9258.0
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0

In [8]:
modified_df_fill_median.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0,NaN,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72.0,4200.0,31,39,18344.0
1,1,128.0,nissan,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,NaN,5200.0,31,37,7799.0
2,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750.0
3,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,NaN,4800.0,28,34,9258.0
4,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0

### 2. **Removing Duplicates**

In [9]:
initial_count = modified_df.shape[0]
modified_df = modified_df.drop_duplicates()
remaining_count = modified_df.shape[0]

initial_count, remaining_count

(210, 204)

### 3. **Correcting Inconsistent Values**

In [10]:
inconsistent_values = modified_df["fuel-type"].value_counts()

modified_df['fuel-type'] = (
    modified_df["fuel-type"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        "petrol": "gas",
        "gasoline": "gas"
    })
)

inconsistent_values, modified_df['fuel-type'].value_counts()

(fuel-type
 gas       180
 diesel     20
 water       4
 Name: count, dtype: int64,
 fuel-type
 gas       180
 diesel     20
 water       4
 Name: count, dtype: int64)

### 4. **Handling Outliers**

Interquartile Range (IQR) can be used to detect outliers. A common rule of thumb is that any data point that falls below Q1 - 1.5 x IQR or above Q3 + 1.5 X IQR might be considedred an outlier.

In [11]:
# Use IQR to identify and remove outliers in the 'price' column
Q1 = modified_df['price'].quantile(0.25)
Q3 = modified_df['price'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Remove outliers
modified_df_no_outliers = modified_df[(modified_df['price'] >= lower_bound) & (modified_df['price'] <= upper_bound)]

len(modified_df), len(modified_df_no_outliers)

(204, 171)